Repository ExtendRealityLtd/Zinnia.Unity, pull requests merged in 2018-06, with the labels that each got.

#111 fix(Pointer): update prefabs to use new follow modifier structure
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
Labels: w_inprogress

#116 refactor(Structure): favour List types over arrays for public fields
  .github/CONTRIBUTING.md
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterInternalSetup.cs
  Scripts/Action/CompoundAndAction.cs
  Scripts/Extension/IEnumerableExtensions.cs
  Scripts/Extension/IEnumerableExtensions.cs.meta
  Scripts/Process/MomentProcessor.cs
  Scripts/Process/SourceTargetProcessor.cs
  Scripts/Tracking/Velocity/VelocityTrackerProcessor.cs
  Scripts/Tracking/XrDeviceRelationActivator.cs
  Tests/Editor/Action/CompoundAndActionTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
  Tests/Editor/Tracking/GameObjectStateMirrorTest.cs
  Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
  Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
Labels: w_inprogress

#117 chore(Visual): rename camera overlay events
  Scripts/Visual/CameraColorOverlay.cs
  Tests/Editor/Visual/CameraColorOverlayTest.cs
Labels: w_inprogress

#114 Feat/follow modifiers - resolves #22
  Scripts/Tracking/Follow/Modifier/ModifyRigidbodyVelocity.cs
  Scripts/Tracking/Follow/Modifier/ModifyRigidbodyVelocity.cs.meta
  Scripts/Tracking/Follow/Modifier/ModifyTransform.cs
  Tests/Editor/Tracking/Follow/Modifier/ModifyRigidbodyVelocityTest.cs
  Tests/Editor/Tracking/Follow/Modifier/ModifyRigidbodyVelocityTest.cs.meta
Labels: w_inprogress

#120 Chore/events overhaul
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterInternalSetup.cs
  Prefabs/Locomotion/Teleporters/Teleporter.Dash.SnapToFloor.prefab
  Prefabs/Locomotion/Teleporters/Teleporter.Instant.SnapToFloor.prefab
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
  Scripts/Action/BaseAction.cs
  Scripts/Action/BooleanAction.cs
  Scripts/Action/CompoundAndAction.cs
  Scripts/Action/FloatAction.cs
  Scripts/Action/SurfaceChangeAction.cs
  Scripts/Action/ToggleAction.cs
  Scripts/Action/Vector2Action.cs
  Scripts/Cast/ParabolicLineCast.cs
  Scripts/Cast/PointsCast.cs
  Scripts/Cast/StraightLineCast.cs
  Scripts/Extension/Vector2Extensions.cs
  Scripts/Extension/Vector2Extensions.cs.meta
  Scripts/Input/UnityAxis1DAction.cs
  Scripts/Input/UnityAxis2DAction.cs
  Scripts/Input/UnityButtonAction.cs
  Scripts/Pointer/ObjectPointer.cs
  Scripts/Process/MomentProcessor.cs
  Scripts/Tracking/CollisionTracker.cs
  Scripts/Tracking/Follow/Modifier/SourceFollowActiveTarget.cs
  Scripts/Tracking/Follow/Modifier/TargetsFollowSource.cs
  Scripts/Tracking/Follow/ObjectFollow.cs
  Scripts/Tracking/PointNormalRotator.cs
  Scripts/Tracking/SurfaceLocator.cs
  Scripts/Tracking/TransformModify.cs
  Scripts/Tracking/Velocity/VelocityEstimator.cs
  Scripts/Visual/CameraColorOverlay.cs
  Scripts/Visual/PointsRenderer.cs
  Tests/Editor/Action/BooleanActionTest.cs
  Tests/Editor/Action/CompoundAndActionTest.cs
  Tests/Editor/Action/FloatActionTest.cs
  Tests/Editor/Action/SurfaceChangeActionTest.cs
  Tests/Editor/Action/ToggleActionTest.cs
  Tests/Editor/Action/Vector2ActionTest.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Extension/Vector2ExtensionsTest.cs
  Tests/Editor/Extension/Vector2ExtensionsTest.cs.meta
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Tracking/PointNormalRotatorTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs
Labels: w_inreview

#122 fix(events): ensure digested event data is not mutated
  Scripts/Cast/PointsCast.cs
  Scripts/Pointer/ObjectPointer.cs
  Scripts/Tracking/CollisionTracker.cs
  Scripts/Tracking/Follow/ObjectFollow.cs
  Scripts/Tracking/TransformModify.cs
  Scripts/Visual/CameraColorOverlay.cs
Labels: w_inprogress

#124 chore(Tracking): collision tracker events
  Scripts/Tracking/CollisionTracker.cs
Labels: chore, w_inreview

#123 refactor(Velocity): move common calls into base class
  Scripts/Tracking/Velocity/VelocityEstimator.cs
  Scripts/Tracking/Velocity/VelocityTracker.cs
  Scripts/Tracking/Velocity/VelocityTrackerProcessor.cs
  Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
Labels: w_inprogress

#121 refactor(Follow): reduce duplicate code in follow modifiers
  Scripts/Tracking/Follow/Modifier/FollowModifier.cs
  Scripts/Tracking/Follow/Modifier/ModifyRigidbodyVelocity.cs
  Scripts/Tracking/Follow/Modifier/ModifyTransform.cs
  Scripts/Tracking/Follow/Modifier/SourceFollowActiveTarget.cs
  Scripts/Tracking/Follow/Modifier/TargetsFollowSource.cs
  Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
Labels: w_inprogress

#126 fix(Tracking): update enum attribute to UnityFlags in collision tracker
  Scripts/Tracking/CollisionTracker.cs
Labels: w_inprogress

#127 fix(Tracking): add missing collision tracker type check
  Scripts/Tracking/CollisionTracker.cs
Labels: w_inprogress

#129 Feat/xr config
  Prefabs/[UnityXRCameraRig]/Scripts.meta
  Prefabs/[UnityXRCameraRig]/Scripts/Input.meta
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityAxis1DAction.cs
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityAxis1DAction.cs.meta
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityAxis2DAction.cs
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityAxis2DAction.cs.meta
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityButtonAction.cs
  Prefabs/[UnityXRCameraRig]/Scripts/Input/UnityButtonAction.cs.meta
  Prefabs/[UnityXRCameraRig]/Scripts/UnityXRConfiguration.cs
  Prefabs/[UnityXRCameraRig]/Scripts/UnityXRConfiguration.cs.meta
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.LeftControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.RightControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.LeftControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.RightControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/[UnityXRCameraRig].prefab
Labels: w_inprogress

#132 fix(Tracking): explicitly specify time settings for rigidbody tests
  Tests/Editor/Tracking/Follow/Modifier/ModifyRigidbodyVelocityTest.cs
  Tests/Utility/TimeSettingOverride.cs
  Tests/Utility/TimeSettingOverride.cs.meta
Labels: w_inprogress

#133 Chore/test fixes
  Tests/Editor/Action/BooleanActionTest.cs
  Tests/Editor/Action/CompoundAndActionTest.cs
  Tests/Editor/Action/FloatActionTest.cs
  Tests/Editor/Action/SurfaceChangeActionTest.cs
  Tests/Editor/Action/ToggleActionTest.cs
  Tests/Editor/Action/Vector2ActionTest.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Data/Type/SurfaceDataTest.cs
  Tests/Editor/Data/Type/TransformDataTest.cs
  Tests/Editor/Data/Type/Vector3StateTest.cs
  Tests/Editor/Extension/ComponentExtensionsTest.cs
  Tests/Editor/Extension/FloatExtensionsTest.cs
  Tests/Editor/Extension/Vector2ExtensionsTest.cs
  Tests/Editor/Extension/Vector3ExtensionsTest.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Tracking/Follow/Modifier/ModifyRigidbodyVelocityTest.cs
  Tests/Editor/Tracking/Follow/Modifier/ModifyTransformTest.cs
  Tests/Editor/Tracking/Follow/Modifier/TransformSourceFollowActiveTargetTest.cs
  Tests/Editor/Tracking/Follow/Modifier/TransformTargetsFollowSourceTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
  Tests/Editor/Tracking/GameObjectStateMirrorTest.cs
  Tests/Editor/Tracking/PointNormalRotatorTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
  Tests/Editor/Tracking/TransformModifyTest.cs
  Tests/Editor/Tracking/Velocity/ApplyVelocityTest.cs
  Tests/Editor/Tracking/Velocity/VelocityEstimatorTest.cs
  Tests/Editor/Tracking/Velocity/VelocityMultiplierTest.cs
  Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
  Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
  Tests/Editor/Utility/BezierCurveGeneratorTest.cs
  Tests/Editor/Utility/ExclusionRuleTest.cs
  Tests/Editor/Visual/CameraColorOverlayTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs
  Tests/Utility/Mock/UnityEventListenerMock.cs
  Tests/Utility/Mock/VelocityTrackerMock.cs
  Tests/Utility/Stub/ExclusionRuleStub.cs
  Tests/Utility/TimeSettingOverride.cs
Labels: w_inprogress

#136 fix(Velocity): use global space instead of local for calculations - fixes #119
  Scripts/Tracking/Velocity/VelocityEstimator.cs
Labels: w_inprogress

#135 Feat/pointer prefab helper
  Prefabs/Locomotion/Teleporters/SharedResources.meta
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts.meta
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterInternalSetup.cs
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterInternalSetup.cs.meta
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterUserSetup.cs
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterUserSetup.cs.meta
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
  Prefabs/Pointers/SharedResources/Scripts.meta
  Prefabs/Pointers/SharedResources/Scripts/PointerInternalSetup.cs
  Prefabs/Pointers/SharedResources/Scripts/PointerInternalSetup.cs.meta
  Prefabs/Pointers/SharedResources/Scripts/PointerUserSetup.cs
  Prefabs/Pointers/SharedResources/Scripts/PointerUserSetup.cs.meta
Labels: w_inreview

#134 Feat/list processing
  Scripts/Process/Component.meta
  Scripts/Process/Component/SourceTargetProcessor.cs
  Scripts/Process/Component/SourceTargetProcessor.cs.meta
  Scripts/Process/Moment.meta
  Scripts/Process/Moment/MomentProcess.cs
  Scripts/Process/Moment/MomentProcess.cs.meta
  Scripts/Process/Moment/MomentProcessor.cs
  Scripts/Process/Moment/MomentProcessor.cs.meta
  Scripts/Tracking/Collision/Collection.meta
  Scripts/Tracking/Collision/Collection/ActiveCollisionsContainer.cs
  Scripts/Tracking/Collision/Collection/ActiveCollisionsContainer.cs.meta
  Scripts/Tracking/Collision/Collection/Operation.meta
  Scripts/Tracking/Collision/Collection/Operation/NearestSorter.cs
  Scripts/Tracking/Collision/Collection/Operation/NearestSorter.cs.meta
  Scripts/Tracking/Collision/Collection/Operation/OrderReverser.cs
  Scripts/Tracking/Collision/Collection/Operation/OrderReverser.cs.meta
  Scripts/Tracking/Collision/Collection/Operation/Slicer.cs
  Scripts/Tracking/Collision/Collection/Operation/Slicer.cs.meta
  Scripts/Tracking/Collision/CollisionNotifier.cs
  Scripts/Tracking/Follow/ObjectFollow.cs
  Scripts/Tracking/GameObjectStateMirror.cs
  Tests/Editor/Tracking/Collision.meta
  Tests/Editor/Tracking/Collision/Collection.meta
  Tests/Editor/Tracking/Collision/Collection/ActiveCollisionsContainerTest.cs
  Tests/Editor/Tracking/Collision/Collection/ActiveCollisionsContainerTest.cs.meta
  Tests/Editor/Tracking/Collision/Collection/Operation.meta
  Tests/Editor/Tracking/Collision/Collection/Operation/NearestSorterTest.cs
  Tests/Editor/Tracking/Collision/Collection/Operation/NearestSorterTest.cs.meta
  Tests/Editor/Tracking/Collision/Collection/Operation/OrderReverserTest.cs
  Tests/Editor/Tracking/Collision/Collection/Operation/OrderReverserTest.cs.meta
  Tests/Editor/Tracking/Collision/Collection/Operation/SlicerTest.cs
  Tests/Editor/Tracking/Collision/Collection/Operation/SlicerTest.cs.meta
  Tests/Utility/Helper.meta
  Tests/Utility/Helper/ActiveCollisionsHelper.cs
  Tests/Utility/Helper/ActiveCollisionsHelper.cs.meta
  Tests/Utility/Helper/CollisionNotifierHelper.cs
  Tests/Utility/Helper/CollisionNotifierHelper.cs.meta
Labels: w_inreview
