Repository ExtendRealityLtd/Zinnia.Unity, pull requests merged in 2018-08, with the labels that each got.

#147 chore(Tracking): make camera rig alias a core component
  Prefabs/CameraRig/TrackedAlias/SharedResources/Scripts/TrackedAliasFacade.cs
  Prefabs/CameraRig/[UnityXRCameraRig]/[UnityXRCameraRig].prefab
  Scripts/Tracking/CameraRig.meta
  Scripts/Tracking/CameraRig/BaseAliasAssociationCollection.cs
  Scripts/Tracking/CameraRig/BaseAliasAssociationCollection.cs.meta
  Scripts/Tracking/CameraRig/LinkedAliasAssociationCollection.cs
  Scripts/Tracking/CameraRig/LinkedAliasAssociationCollection.cs.meta
Labels: w_inreview

#143 feat(Utility): disable or enable components by type - resolves #28
  Scripts/Utility/BehaviourEnabledSetter.cs
  Scripts/Utility/BehaviourEnabledSetter.cs.meta
  Tests/Editor/Utility/BehaviourEnabledSetterTest.cs
  Tests/Editor/Utility/BehaviourEnabledSetterTest.cs.meta
Labels: w_inprogress

#142 feat(Association): extract common functionality for reusability
  Scripts/Association.meta
  Scripts/Association/BaseGameObjectsAssociation.cs
  Scripts/Association/BaseGameObjectsAssociation.cs.meta
  Scripts/Association/GameObjectsAssociationActivator.cs
  Scripts/Association/GameObjectsAssociationActivator.cs.meta
  Scripts/Association/LoadedXrDeviceAssociation.cs
  Scripts/Association/LoadedXrDeviceAssociation.cs.meta
  Scripts/Tracking/XrDeviceRelationActivator.cs
  Tests/Editor/Association.meta
  Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
  Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs.meta
  Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
Labels: enhancement, w_inreview

#149 Chore/compiler warnings
  Scripts/Utility/CountdownTimer.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocityTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocityTest.cs
Labels: chore, w_inreview

#151 Chore/extension work
  Scripts/Extension/GameObjectExtensions.cs
  Scripts/Extension/TransformDataExtensions.cs
  Scripts/Extension/TransformDataExtensions.cs.meta
  Scripts/Extension/TransformExtensions.cs
  Scripts/Tracking/Modification/TransformPropertyApplier.cs
  Tests/Editor/Extension/ColliderExtensionsTest.cs
  Tests/Editor/Extension/ColliderExtensionsTest.cs.meta
  Tests/Editor/Extension/ComponentExtensionsTest.cs
  Tests/Editor/Extension/GameObjectExtensionsTest.cs
  Tests/Editor/Extension/GameObjectExtensionsTest.cs.meta
  Tests/Editor/Extension/IEnumerableExtensionsTest.cs
  Tests/Editor/Extension/IEnumerableExtensionsTest.cs.meta
  Tests/Editor/Extension/TransformDataExtensionsTest.cs
  Tests/Editor/Extension/TransformDataExtensionsTest.cs.meta
  Tests/Editor/Extension/TransformExtensionsTest.cs
  Tests/Editor/Extension/TransformExtensionsTest.cs.meta
  Tests/Editor/Tracking/Modification/TransformPropertyApplierTest.cs
Labels: w_inreview

#153 Chore/prefab fixing
  Prefabs/CameraRig/UnityXRCameraRig.meta
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings.meta
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.Oculus.LeftController.prefab
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.Oculus.LeftController.prefab.meta
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.Oculus.RightController.prefab
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.Oculus.RightController.prefab.meta
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.OpenVR.LeftController.prefab
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.OpenVR.LeftController.prefab.meta
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.OpenVR.RightController.prefab
  Prefabs/CameraRig/UnityXRCameraRig/InputMappings/UnityXR.OpenVR.RightController.prefab.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityAxis1DAction.cs
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityAxis1DAction.cs.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityAxis2DAction.cs
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityAxis2DAction.cs.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityButtonAction.cs
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/Input/UnityButtonAction.cs.meta
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/UnityXRConfiguration.cs
  Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/UnityXRConfiguration.cs.meta
  Prefabs/CameraRig/UnityXRCameraRig/[UnityXRCameraRig].prefab
  Prefabs/CameraRig/UnityXRCameraRig/[UnityXRCameraRig].prefab.meta
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
  Prefabs/Pointers/SharedResources/Scripts/PointerFacade.cs
  Prefabs/Pointers/SharedResources/Scripts/PointerInternalSetup.cs
Labels: w_inprogress

#154 Feat/teleport facade validity
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterFacade.cs
  Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterInternalSetup.cs
  Prefabs/Locomotion/Teleporters/Teleporter.Dash.SnapToFloor.prefab
  Prefabs/Locomotion/Teleporters/Teleporter.Instant.SnapToFloor.prefab
  Scripts/Visual/CameraColorOverlay.cs
Labels: w_inprogress

#155 Fix/buggles
  Prefabs/Interactions/Interactables/Interactable.Touch.Grab.prefab
  Scripts/Cast/PhysicsCast.cs
  Scripts/Tracking/SurfaceLocator.cs
Labels: w_inprogress

#156 Chore/stuffs
  Prefabs/Interactions/Interactables/Interactable.Touch.Grab.ControlDirection.prefab
  Prefabs/Interactions/Interactables/Interactable.Touch.Grab.UniformScale.prefab
  Prefabs/Interactions/Interactables/Interactable.Touch.Grab.prefab
  Scripts/Data/Attribute/Editor/MinMaxRangeDrawer.cs
  Scripts/Data/Attribute/Editor/MinMaxRangeDrawer.cs.meta
  Scripts/Data/Attribute/MinMaxRangeAttribute.cs
  Scripts/Data/Attribute/MinMaxRangeAttribute.cs.meta
  Scripts/Data/Type/Editor/FloatRangeDrawer.cs
  Scripts/Data/Type/Editor/FloatRangeDrawer.cs.meta
  Scripts/Data/Type/FloatRange.cs
  Scripts/Data/Type/FloatRange.cs.meta
  Scripts/Data/Type/Transformation/FloatToBoolean.cs
  Scripts/Data/Type/Transformation/FloatToBoolean.cs.meta
  Scripts/Lib.meta
  Scripts/Lib/Supyrb.meta
  Scripts/Lib/Supyrb/SerializedPropertyExtensions.cs
  Scripts/Lib/Supyrb/SerializedPropertyExtensions.cs.meta
  Scripts/Tracking/Modification/PinchScaler.cs
  Tests/Editor/Data/Type/FloatRangeTest.cs
  Tests/Editor/Data/Type/FloatRangeTest.cs.meta
  Tests/Editor/Data/Type/Transformation/FloatToBooleanTest.cs
  Tests/Editor/Data/Type/Transformation/FloatToBooleanTest.cs.meta
Labels: w_inprogress

#160 chore(Editor): ensure prefab changes are shown - resolves #159
  Scripts/Data/Attribute/Editor/MinMaxRangeDrawer.cs
  Scripts/Data/Attribute/Editor/UnityFlagsDrawer.cs
  Scripts/Data/Type/Editor/FloatRangeDrawer.cs
  Scripts/Data/Type/Editor/Vector3StateDrawer.cs
Labels: w_inprogress
