Repository ExtendRealityLtd/Zinnia.Unity, pull requests merged in 2018-05, with the labels that each got.

#70 feat(Visual): add camera color overlay - fixes #5
  Resources.meta
  Resources/Materials.meta
  Resources/Materials/CameraColorOverlay.mat
  Resources/Materials/CameraColorOverlay.mat.meta
  Resources/Shaders.meta
  Resources/Shaders/Unlit_TransparentColor.shader
  Resources/Shaders/Unlit_TransparentColor.shader.meta
  Scripts/Visual.meta
  Scripts/Visual/CameraColorOverlay.cs
  Scripts/Visual/CameraColorOverlay.cs.meta
Labels: w_inprogress

#73 fix(events): ensure all UnityEvents are instantiated to prevent nulls
  Scripts/Tracking/Follow/ObjectFollow.cs
  Scripts/Tracking/TransformModify.cs
  Scripts/Visual/CameraColorOverlay.cs
Labels: w_inprogress

#74 fix(tests): call DestroyImmediate in teardown for created scene objects
  Tests/Editor/Tracking/Follow/Modifier/TransformSourceFollowActiveTargetTest.cs
  Tests/Editor/Tracking/Follow/Modifier/TransformTargetsFollowSourceTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
  Tests/Editor/Tracking/TransformModifyTest.cs
  Tests/Editor/Tracking/Velocity/VelocityEstimatorTest.cs
  Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
Labels: w_inprogress

#72 Feat/input actions - fixes #9 fixes #10 fixes #11
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.LeftControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.LeftControllerButtonMap.prefab.meta
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.RightControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.Oculus.RightControllerButtonMap.prefab.meta
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.LeftControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.LeftControllerButtonMap.prefab.meta
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.RightControllerButtonMap.prefab
  Prefabs/[UnityXRCameraRig]/UnityXR.OpenVR.RightControllerButtonMap.prefab.meta
  Scripts/Action.meta
  Scripts/Action/BaseAction.cs
  Scripts/Action/BaseAction.cs.meta
  Scripts/Action/BooleanAction.cs
  Scripts/Action/BooleanAction.cs.meta
  Scripts/Action/CompoundAndAction.cs
  Scripts/Action/CompoundAndAction.cs.meta
  Scripts/Action/FloatAction.cs
  Scripts/Action/FloatAction.cs.meta
  Scripts/Action/ToggleAction.cs
  Scripts/Action/ToggleAction.cs.meta
  Scripts/Action/Vector2Action.cs
  Scripts/Action/Vector2Action.cs.meta
  Scripts/Input.meta
  Scripts/Input/UnityAxis1DAction.cs
  Scripts/Input/UnityAxis1DAction.cs.meta
  Scripts/Input/UnityAxis2DAction.cs
  Scripts/Input/UnityAxis2DAction.cs.meta
  Scripts/Input/UnityButtonAction.cs
  Scripts/Input/UnityButtonAction.cs.meta
  Tests/Editor/Action.meta
  Tests/Editor/Action/BooleanActionTest.cs
  Tests/Editor/Action/BooleanActionTest.cs.meta
  Tests/Editor/Action/CompoundAndActionTest.cs
  Tests/Editor/Action/CompoundAndActionTest.cs.meta
  Tests/Editor/Action/FloatActionTest.cs
  Tests/Editor/Action/FloatActionTest.cs.meta
  Tests/Editor/Action/ToggleActionTest.cs
  Tests/Editor/Action/ToggleActionTest.cs.meta
  Tests/Editor/Action/Vector2ActionTest.cs
  Tests/Editor/Action/Vector2ActionTest.cs.meta
  Tests/Utility.meta
  Tests/Utility/Mock.meta
  Tests/Utility/Mock/UnityEventListenerMock.cs
  Tests/Utility/Mock/UnityEventListenerMock.cs.meta
Labels: w_inprogress

#78 feat(Tracking): mirror game object active state to other game objects
  Scripts/Tracking/GameObjectStateMirror.cs
  Scripts/Tracking/GameObjectStateMirror.cs.meta
  Tests/Editor/Tracking/GameObjectStateMirrorTest.cs
  Tests/Editor/Tracking/GameObjectStateMirrorTest.cs.meta
Labels: w_inreview

#79 feat(XrRelation): (de)activating game objects based on XR device - resolves #13
  Scripts/Tracking/XrDeviceRelationActivator.cs
  Scripts/Tracking/XrDeviceRelationActivator.cs.meta
  Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
  Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs.meta
Labels: w_inprogress

#80 chore(Extension): add tests for component extensions
  Tests/Editor/Extension.meta
  Tests/Editor/Extension/ComponentExtensionsTest.cs
  Tests/Editor/Extension/ComponentExtensionsTest.cs.meta
Labels: w_inprogress

#81 fix(Visual): prevent add from being called twice with same parameters
  Scripts/Visual/CameraColorOverlay.cs
Labels: w_inprogress

#82 Feat/surface locator - fixes #6 - fixes #14
  Scripts/Action/SurfaceChangeAction.cs
  Scripts/Action/SurfaceChangeAction.cs.meta
  Scripts/Data/Type/SurfaceData.cs
  Scripts/Data/Type/SurfaceData.cs.meta
  Scripts/Data/Type/TransformData.cs
  Scripts/Data/Type/TransformData.cs.meta
  Scripts/Extension/Vector3Extensions.cs
  Scripts/Extension/Vector3Extensions.cs.meta
  Scripts/Tracking/SurfaceLocator.cs
  Scripts/Tracking/SurfaceLocator.cs.meta
  Scripts/Tracking/TransformModify.cs
  Scripts/Utility/ExclusionRule.cs
  Scripts/Utility/ExclusionRule.cs.meta
  Scripts/Utility/PhysicsCast.cs
  Scripts/Utility/PhysicsCast.cs.meta
  Tests/Editor/Action/SurfaceChangeActionTest.cs
  Tests/Editor/Action/SurfaceChangeActionTest.cs.meta
  Tests/Editor/Data/Type/SurfaceDataTest.cs
  Tests/Editor/Data/Type/SurfaceDataTest.cs.meta
  Tests/Editor/Data/Type/TransformDataTest.cs
  Tests/Editor/Data/Type/TransformDataTest.cs.meta
  Tests/Editor/Extension/Vector3ExtensionsTest.cs
  Tests/Editor/Extension/Vector3ExtensionsTest.cs.meta
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs.meta
  Tests/Editor/Tracking/TransformModifyTest.cs
  Tests/Editor/Utility.meta
  Tests/Editor/Utility/ExclusionRuleTest.cs
  Tests/Editor/Utility/ExclusionRuleTest.cs.meta
Labels: w_inprogress

#85 chore(testing): add event tests - fixes #76
  Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
  Tests/Editor/Tracking/TransformModifyTest.cs
  Tests/Editor/Visual.meta
  Tests/Editor/Visual/CameraColorOverlayTest.cs
  Tests/Editor/Visual/CameraColorOverlayTest.cs.meta
Labels: w_inprogress

#93 Fix/null n bits
  Scripts/Process/MomentProcessor.cs
  Scripts/Process/SourceTargetProcessor.cs
  Scripts/Tracking/Follow/ObjectFollow.cs
  Scripts/Tracking/SurfaceLocator.cs
Labels: w_inprogress

#95 feat(Pointer): add straight and parabolic object pointers - fixes #8 fixes #7
  Prefabs/Pointers.meta
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab.meta
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
  Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab.meta
  Prefabs/Pointers/SharedResources.meta
  Prefabs/Pointers/SharedResources/Materials.meta
  Prefabs/Pointers/SharedResources/Materials/PointerDefaultInvalid.mat
  Prefabs/Pointers/SharedResources/Materials/PointerDefaultInvalid.mat.meta
  Prefabs/Pointers/SharedResources/Materials/PointerDefaultValid.mat
  Prefabs/Pointers/SharedResources/Materials/PointerDefaultValid.mat.meta
  Scripts/Cast.meta
  Scripts/Cast/ParabolicLineCast.cs
  Scripts/Cast/ParabolicLineCast.cs.meta
  Scripts/Cast/PhysicsCast.cs
  Scripts/Cast/PhysicsCast.cs.meta
  Scripts/Cast/PointsCast.cs
  Scripts/Cast/PointsCast.cs.meta
  Scripts/Cast/StraightLineCast.cs
  Scripts/Cast/StraightLineCast.cs.meta
  Scripts/Extension/TransformExtensions.cs
  Scripts/Extension/TransformExtensions.cs.meta
  Scripts/Pointer.meta
  Scripts/Pointer/ObjectPointer.cs
  Scripts/Pointer/ObjectPointer.cs.meta
  Scripts/Tracking/PointNormalRotator.cs
  Scripts/Tracking/PointNormalRotator.cs.meta
  Scripts/Tracking/SurfaceLocator.cs
  Scripts/Tracking/TransformModify.cs
  Scripts/Utility/BezierCurveGenerator.cs
  Scripts/Utility/BezierCurveGenerator.cs.meta
  Scripts/Visual/PointsRenderer.cs
  Scripts/Visual/PointsRenderer.cs.meta
  Tests/Editor/Cast.meta
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs.meta
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs.meta
  Tests/Editor/Pointer.meta
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs.meta
  Tests/Editor/Tracking/PointNormalRotatorTest.cs
  Tests/Editor/Tracking/PointNormalRotatorTest.cs.meta
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
  Tests/Editor/Utility/BezierCurveGeneratorTest.cs
  Tests/Editor/Utility/BezierCurveGeneratorTest.cs.meta
  Tests/Editor/Visual/PointsRendererTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs.meta
  Tests/Utility/Stub.meta
  Tests/Utility/Stub/ExclusionRuleStub.cs
  Tests/Utility/Stub/ExclusionRuleStub.cs.meta
Labels: w_inprogress

#94 feat(Tracking): collision tracking
  Scripts/Tracking/CollisionTracker.cs
  Scripts/Tracking/CollisionTracker.cs.meta
Labels: feature, w_inreview

#103 fix(Pointer): remove reliance on cast data for invalid state
  Scripts/Pointer/ObjectPointer.cs
Labels: w_inreview

#102 Feat/teleporters - fixes #98
  Prefabs/Locomotion.meta
  Prefabs/Locomotion/Teleporters.meta
  Prefabs/Locomotion/Teleporters/Scripts.meta
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterInternalSetup.cs
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterInternalSetup.cs.meta
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterUserSetup.cs
  Prefabs/Locomotion/Teleporters/Scripts/TeleporterUserSetup.cs.meta
  Prefabs/Locomotion/Teleporters/Teleporter.Dash.SnapToFloor.prefab
  Prefabs/Locomotion/Teleporters/Teleporter.Dash.SnapToFloor.prefab.meta
  Prefabs/Locomotion/Teleporters/Teleporter.Instant.SnapToFloor.prefab
  Prefabs/Locomotion/Teleporters/Teleporter.Instant.SnapToFloor.prefab.meta
  Scripts/Data/Type/CameraList.cs
  Scripts/Data/Type/CameraList.cs.meta
  Scripts/Visual/CameraColorOverlay.cs
Labels: w_inprogress

#105 fix(Pointer): ensure exit/deactivate events are called in correct order
  Scripts/Pointer/ObjectPointer.cs
Labels: w_inreview
