Repository ExtendRealityLtd/Zinnia.Unity, pull requests merged in 2019-02, with the labels that each got.

#273 chore(Tracking): fix case of property name
  Runtime/Tracking/Follow/Modifier/Property/PropertyModifier.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocityTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Position/TransformPositionTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocityTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformRotationTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Scale/TransformScaleTest.cs
Labels: w_inprogress

#275 chore(Tracking): fix missing XML parameter documentation
  Runtime/Tracking/Modification/TransformPropertyApplier.cs
Labels: chore, w_inprogress

#276 feat(Data): add shorthand Vector3State options
  Runtime/Data/Type/Vector3State.cs
  Tests/Editor/Data/Type/Vector3StateTest.cs
Labels: w_inprogress

#277 feat(Data): add zero value shortcut to FloatRange
  Runtime/Data/Type/FloatRange.cs
  Tests/Editor/Data/Type/FloatRangeTest.cs
Labels: w_inprogress

#278 fix(Modification): add threshold to destination equality check on lerp
  Runtime/Tracking/Modification/TransformPropertyApplier.cs
Labels: w_inprogress

#279 feat(Transformation): ability to restrict the values of a Vector3
  Runtime/Data/Type/Transformation/Vector3Restrictor.cs
  Runtime/Data/Type/Transformation/Vector3Restrictor.cs.meta
  Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
  Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs.meta
Labels: w_inprogress

#280 feat(Follow): rotate target by following position change of source
  Runtime/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotation.cs
  Runtime/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotation.cs.meta
  Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotationTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotationTest.cs.meta
Labels: w_inprogress

#281 feat(Velocity): ability to apply artificial velocities to an object
  Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs
  Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs.meta
  Runtime/Tracking/Velocity/VelocityApplier.cs
Labels: w_inprogress

#283 chore(Dependencies): update Malimbe to version 8.2.0
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.PropertySerializationAttribute.Fody.dll
  Dependencies/Malimbe/README.md
  Dependencies/Malimbe/package.json
Labels: w_inprogress

#284 chore(structure): fix invalid XML documentation comments
  Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs
Labels: chore, w_inprogress

#285 Fix/malimbe issues
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.BehaviourStateRequirementMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberClearanceMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.PropertySerializationAttribute.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.PropertySetterMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.PropertyValidationMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.XmlDocumentationAttribute.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Tracking/Collision/Active/ActiveCollisionsContainer.cs
Labels: w_inreview

#286 chore(tests): fix warning log for Vector3RestrictorTest
  Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
Labels: w_inprogress

#287 Fix/observable collection events
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Data/Collection/ObservableSet.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
  Tests/Editor/Data/Collection/GameObjectObservableSetTest.cs
Labels: w_inreview

#289 feat(Data): add GameObject cloner
  Runtime/Data/Operation/GameObjectCloner.cs
  Runtime/Data/Operation/GameObjectCloner.cs.meta
  Tests/Editor/Data/Operation/GameObjectClonerTest.cs
  Tests/Editor/Data/Operation/GameObjectClonerTest.cs.meta
  Tests/Editor/Tracking/Follow/ObjectDistanceComparatorEventDataExtractorTest.cs
  Tests/Utility/Mock/UnityEventListenerMock.cs
  Tests/Utility/Mock/UnityEventValueListenerMock.cs
  Tests/Utility/Mock/UnityEventValueListenerMock.cs.meta
Labels: w_inreview

#288 feat(Tracking): add extractor for collision target
  Runtime/Tracking/Collision/Active/Operation/NotifierTargetExtractor.cs
  Runtime/Tracking/Collision/Active/Operation/NotifierTargetExtractor.cs.meta
  Tests/Editor/Tracking/Collision/Active/Operation/NotifierTargetExtractorTest.cs
  Tests/Editor/Tracking/Collision/Active/Operation/NotifierTargetExtractorTest.cs.meta
Labels: w_inreview

#290 Perf/garbage collected allocations
  Editor/Rule/RuleContainerDrawer.cs
  Editor/Utility/InterfaceContainerDrawer.cs
  Runtime/Action/Action.cs
  Runtime/Action/AllAction.cs
  Runtime/Action/AnyAction.cs
  Runtime/Association/GameObjectsAssociationActivator.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Data/Collection/ObservableCounter.cs
  Runtime/Data/Type/Transformation/FloatAdder.cs
  Runtime/Data/Type/Transformation/FloatMultiplier.cs
  Runtime/Data/Type/Transformation/Vector2Multiplier.cs
  Runtime/Data/Type/Transformation/Vector3Multiplier.cs
  Runtime/Data/Type/Transformation/Vector3Subtractor.cs
  Runtime/Extension/IEnumerableExtensions.cs
  Runtime/Extension/IEnumerableExtensions.cs.meta
  Runtime/Haptics/HapticProcessor.cs
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Process/Component/SourceTargetProcessor.cs
  Runtime/Process/Moment/MomentProcessor.cs
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyComponentTypeRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/AnyTagRule.cs
  Runtime/Rule/RulesMatcher.cs
  Runtime/Tracking/Collision/Active/ActiveCollisionPublisher.cs
  Runtime/Tracking/Collision/Active/Operation/Slicer.cs
  Runtime/Tracking/Collision/CollisionNotifier.cs
  Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
  Runtime/Tracking/Modification/TransformPropertyApplier.cs
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Runtime/Tracking/SurfaceLocator.cs
  Runtime/Tracking/Velocity/VelocityTrackerProcessor.cs
  Runtime/Tracking/Velocity/XRNodeVelocityEstimator.cs
  Runtime/Visual/PointsRenderer.cs
  Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
  Tests/Editor/Extension/IEnumerableExtensionsTest.cs
  Tests/Editor/Extension/IEnumerableExtensionsTest.cs.meta
  Tests/Editor/Visual/PointsRendererTest.cs
Labels: enhancement, w_inreview

#294 fix(Tracking): float comparisons
  Runtime/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocity.cs
  Runtime/Tracking/Modification/DirectionModifier.cs
Labels: w_inreview

#295 chore(Tests): fix wrong attribute usage
  Tests/Utility/TimeSettingOverride.cs
Labels: chore, w_inreview

#297 chore(Dependencies): update Malimbe to version 8.2.3
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.dll
  Dependencies/Malimbe/package.json
Labels: chore, w_inprogress

#293 Perf/improvements
  Dependencies/Supyrb/Editor/SerializedPropertyExtensions.cs
  Editor/Data/Attribute/MinMaxRangeAttributeDrawer.cs
  Editor/Data/Type/FloatRangeDrawer.cs
  Editor/Data/Type/Vector3StateDrawer.cs
  Editor/Rule/RuleContainerDrawer.cs
  Editor/Utility/TypePickerWindow.cs
  Runtime/Action/Action.cs
  Runtime/Association/GameObjectsAssociationActivator.cs
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/PointsCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Data/Collection/ObservableSet.cs
  Runtime/Extension/ColliderExtensions.cs
  Runtime/Haptics/AudioClipHapticPulser.cs
  Runtime/Haptics/XRNodeHapticPulser.cs
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Tracking/Collision/Active/ActiveCollisionConsumer.cs
  Runtime/Tracking/Collision/Active/ActiveCollisionPublisher.cs
  Runtime/Tracking/Collision/Active/ActiveCollisionsContainer.cs
  Runtime/Tracking/Collision/Active/CollisionPointContainer.cs
  Runtime/Tracking/Collision/Active/Operation/NearestSorter.cs
  Runtime/Tracking/Collision/Active/Operation/OrderReverser.cs
  Runtime/Tracking/Collision/Active/Operation/Slicer.cs
  Runtime/Tracking/Collision/CollisionNotifier.cs
  Runtime/Tracking/Follow/Modifier/FollowModifier.cs
  Runtime/Tracking/Follow/Modifier/Property/PropertyModifier.cs
  Runtime/Tracking/Follow/Modifier/Property/Rotation/RigidbodyForceAtPosition.cs
  Runtime/Tracking/Follow/ObjectDistanceComparator.cs
  Runtime/Tracking/Modification/DirectionModifier.cs
  Runtime/Tracking/Modification/TransformPropertyApplier.cs
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Runtime/Tracking/Query/PointingQuery.cs
  Runtime/Tracking/SurfaceLocator.cs
  Runtime/Tracking/Velocity/XRNodeVelocityEstimator.cs
  Runtime/Utility/InterfaceContainer.cs
  Runtime/Visual/CameraColorOverlay.cs
  Runtime/Visual/PointsRenderer.cs
  Tests/Editor/Data/Collection/GameObjectObservableStackTest.cs
  Tests/Editor/Event/FloatEventProxyEmitterTest.cs
  Tests/Editor/Extension/FloatExtensionsTest.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Tracking/Collision/Active/CollisionPointContainerTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
  Tests/Editor/Tracking/Velocity/AverageVelocityEstimatorTest.cs
  Tests/Editor/Utility/BezierCurveGeneratorTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs
  Tests/Utility/Mock/VelocityTrackerMock.cs
Labels: w_inreview

#292 fix(Data): convert FloatRange to struct to prevent instancing issues - fixes #291
  Runtime/Data/Type/FloatRange.cs
  Runtime/Data/Type/Transformation/Vector3Restrictor.cs
  Tests/Editor/Data/Type/FloatRangeTest.cs
  Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
Labels: w_inprogress

#298 chore(Dependencies): update Malimbe to version 8.2.4
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.PropertyValidationMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.Shared.dll
  Dependencies/Malimbe/package.json
Labels: chore, w_inprogress

#301 feat(Rule): allow rules to be ignored if the component is disabled
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyLayerRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/GameObjectRule.cs
  Runtime/Rule/ListContainsRule.cs
  Runtime/Rule/NegationRule.cs
  Tests/Editor/Rule/ActiveInHierarchyRuleTest.cs
  Tests/Editor/Rule/AllRuleTest.cs
  Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
  Tests/Editor/Rule/AnyLayerRuleTest.cs
  Tests/Editor/Rule/AnyRuleTest.cs
  Tests/Editor/Rule/ListContainsRuleTest.cs
  Tests/Editor/Rule/NegationRuleTest.cs
Labels: w_inprogress
