Repository ExtendRealityLtd/Zinnia.Unity, pull requests merged in 2019-03, with the labels that each got.

#304 feat(Visual): update all fields to serialized properties
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Visual/CameraColorOverlay.cs
  Runtime/Visual/PointsRenderer.cs
  Tests/Editor/Visual/CameraColorOverlayTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs
Labels: w_inprogress

#306 Feat/is active and enabled change check
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Visual/CameraColorOverlay.cs
  Tests/Editor/Zinnia.Tests.Editor.asmdef
Labels: w_inreview

#309 Fix/property drawers
  Editor/Data/Attribute/InternalSettingAttributeDrawer.cs
  Editor/Data/Attribute/RestrictedAttributeDrawer.cs
  Editor/Data/Attribute/RestrictedAttributeDrawer.cs.meta
  Runtime/Data/Attribute/InternalSettingAttribute.cs
  Runtime/Data/Attribute/RestrictedAttribute.cs
  Runtime/Data/Attribute/RestrictedAttribute.cs.meta
Labels: w_inprogress

#310 feat(Utility): update all fields to be serialized properties
  Runtime/Utility/CountdownTimer.cs
  Runtime/Utility/InterfaceContainer.cs
  Tests/Editor/Utility/CountdownTimerTest.cs
  Tests/Editor/Utility/CountdownTimerTest.cs.meta
Labels: w_inprogress

#311 feat(Collection): add extra functionality to ObservableList
  Runtime/Data/Collection/ObservableList.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
Labels: w_inprogress

#314 Fix/serializable type
  Editor/Data/Attribute/TypePickerAttributeDrawer.cs
  Editor/Utility/SerializedPropertyExtensions.cs
  Editor/Utility/SerializedPropertyExtensions.cs.meta
  Editor/Utility/TypePickerWindow.cs
  Runtime/Data/Type/SerializableType.cs
  Tests/Editor/Data/Type/SerializableTypeTest.cs
  Tests/Editor/Data/Type/SerializableTypeTest.cs.meta
Labels: w_inprogress

#315 feat(Rule): update fields to properties and lists to observable
  Runtime/Data/Collection/DefaultObservableList.cs
  Runtime/Data/Collection/DefaultObservableList.cs.meta
  Runtime/Data/Collection/GameObjectObservableList.cs
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Data/Collection/RuleContainerObservableList.cs
  Runtime/Data/Collection/RuleContainerObservableList.cs.meta
  Runtime/Data/Collection/SerializableTypeObservableList.cs
  Runtime/Data/Collection/SerializableTypeObservableList.cs.meta
  Runtime/Data/Collection/StringObservableList.cs
  Runtime/Data/Collection/StringObservableList.cs.meta
  Runtime/Data/Collection/UnityObjectObservableList.cs
  Runtime/Data/Collection/UnityObjectObservableList.cs.meta
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyComponentTypeRule.cs
  Runtime/Rule/AnyLayerRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/AnyTagRule.cs
  Runtime/Rule/ListContainsRule.cs
  Runtime/Rule/NegationRule.cs
  Runtime/Rule/RulesMatcher.cs
  Runtime/Rule/RulesMatcherElementObservableList.cs
  Runtime/Rule/RulesMatcherElementObservableList.cs.meta
  Runtime/Utility/InterfaceContainer.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Event/GameObjectEventProxyEmitterTest.cs
  Tests/Editor/Rule/AllRuleTest.cs
  Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
  Tests/Editor/Rule/AnyLayerRuleTest.cs
  Tests/Editor/Rule/AnyRuleTest.cs
  Tests/Editor/Rule/AnyTagRuleTest.cs
  Tests/Editor/Rule/ListContainsRuleTest.cs
  Tests/Editor/Rule/NegationRuleTest.cs
  Tests/Editor/Rule/RulesMatcherTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionsContainerTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
Labels: w_inprogress

#316 fix(Utility): set field instead of property after deserialization
  Runtime/Utility/InterfaceContainer.cs
Labels: w_inprogress

#305 feat(Action): update all fields to serialized properties
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/Editor/Malimbe.XmlDocumentationAttribute.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Action/Action.cs
  Runtime/Action/ActionRegistrar.cs
  Runtime/Action/AllAction.cs
  Runtime/Action/AnyAction.cs
  Runtime/Action/Collection.meta
  Runtime/Action/Collection/ActionObservableList.cs
  Runtime/Action/Collection/ActionObservableList.cs.meta
  Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs
  Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs.meta
  Runtime/Action/FloatAction.cs
  Runtime/Action/StateEmitter.cs
  Runtime/Action/SurfaceChangeAction.cs
  Runtime/Action/Vector2Action.cs
  Runtime/Data/Collection/ObservableList.cs
  Tests/Editor/Action/ActionRegistrarTest.cs
  Tests/Editor/Action/AllActionTest.cs
  Tests/Editor/Action/AnyActionTest.cs
  Tests/Editor/Action/BooleanActionTest.cs
  Tests/Editor/Action/Collection.meta
  Tests/Editor/Action/Collection/ActionRegistrarSourceObservableListTest.cs
  Tests/Editor/Action/Collection/ActionRegistrarSourceObservableListTest.cs.meta
  Tests/Editor/Action/FloatActionTest.cs
  Tests/Editor/Action/StateEmitterTest.cs
  Tests/Editor/Action/SurfaceChangeActionTest.cs
  Tests/Editor/Action/ToggleActionTest.cs
  Tests/Editor/Action/Vector2ActionTest.cs
Labels: w_inreview

#319 feat(Haptics): update fields to properties and lists to observable
  Runtime/Haptics/AudioClipHapticPulser.cs
  Runtime/Haptics/Collection.meta
  Runtime/Haptics/Collection/HapticProcessObservableList.cs
  Runtime/Haptics/Collection/HapticProcessObservableList.cs.meta
  Runtime/Haptics/HapticProcessor.cs
  Runtime/Haptics/HapticPulser.cs
  Runtime/Haptics/TimedHapticProcess.cs
  Runtime/Haptics/XRNodeHapticPulser.cs
Labels: w_inprogress

#320 refactor(Rule): move rule observable lists into rule namespace
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/Collection.meta
  Runtime/Rule/Collection/RuleContainerObservableList.cs
  Runtime/Rule/Collection/RuleContainerObservableList.cs.meta
  Runtime/Rule/Collection/RulesMatcherElementObservableList.cs
  Runtime/Rule/Collection/RulesMatcherElementObservableList.cs.meta
  Runtime/Rule/RulesMatcher.cs
  Tests/Editor/Rule/AllRuleTest.cs
  Tests/Editor/Rule/AnyRuleTest.cs
  Tests/Editor/Rule/RulesMatcherTest.cs
Labels: w_inprogress

#322 fix(tests): ensure created objects are destroyed within the test
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
  Tests/Editor/Data/Collection/GameObjectObservableSetTest.cs
  Tests/Editor/Data/Operation/GameObjectClonerTest.cs
  Tests/Editor/Tracking/Follow/Modifier/FollowModifierTest.cs
  Tests/Editor/Tracking/Follow/Modifier/Property/Scale/TransformScaleTest.cs
  Tests/Editor/Tracking/Modification/GameObjectStateMirrorTest.cs
  Tests/Editor/Tracking/Modification/PinchScalerTest.cs
Labels: w_inprogress

#323 Fix/obslist tests
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
  Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
  Tests/Editor/Rule/AllRuleTest.cs
  Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
  Tests/Editor/Rule/AnyRuleTest.cs
  Tests/Editor/Rule/AnyTagRuleTest.cs
  Tests/Editor/Rule/ListContainsRuleTest.cs
  Tests/Editor/Rule/RulesMatcherTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionsContainerTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
  Tests/Editor/Tracking/Modification/ComponentEnabledStateModifierTest.cs
  Tests/Editor/Tracking/Modification/GameObjectStateMirrorTest.cs
  Tests/Editor/Tracking/Modification/GameObjectStateSwitcherTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
  Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
Labels: w_inprogress

#324 refactor(Collection): add component to serializable type obs list name
  Runtime/Data/Collection/SerializableTypeComponentObservableList.cs
  Runtime/Data/Collection/SerializableTypeComponentObservableList.cs.meta
  Runtime/Rule/AnyComponentTypeRule.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerTest.cs
  Tests/Editor/Tracking/Collision/Active/ActiveCollisionsContainerTest.cs
  Tests/Editor/Tracking/SurfaceLocatorTest.cs
Labels: w_inprogress

#325 feat(Event): update fields to properties and lists to observable
  Runtime/Action/ActionRegistrar.cs
  Runtime/Action/AllAction.cs
  Runtime/Action/AnyAction.cs
  Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs
  Runtime/Data/Collection/BehaviourObservableList.cs
  Runtime/Data/Collection/BehaviourObservableList.cs.meta
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Event/BehaviourEnabledObserver.cs
  Runtime/Event/ComponentGameObjectEmitter.cs
  Runtime/Event/EventProxyEmitter.cs
  Runtime/Event/GameObjectEmitter.cs
  Runtime/Event/RestrictableSingleEventProxyEmitter.cs
  Runtime/Event/SingleEventProxyEmitter.cs
  Runtime/Haptics/HapticProcessor.cs
  Runtime/Process/Component/GameObjectSourceTargetProcessor.cs
  Runtime/Process/Moment/MomentProcessor.cs
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyComponentTypeRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/AnyTagRule.cs
  Runtime/Rule/RulesMatcher.cs
  Runtime/Tracking/Follow/ObjectFollower.cs
  Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
  Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
  Runtime/Tracking/Velocity/VelocityTrackerProcessor.cs
  Tests/Editor/Action/ActionRegistrarTest.cs
  Tests/Editor/Action/Collection/ActionRegistrarSourceObservableListTest.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
  Tests/Editor/Event/BehaviourEnabledObserverTest.cs
  Tests/Editor/Event/BehaviourEnabledObserverTest.cs.meta
  Tests/Editor/Event/GameObjectEventProxyEmitterTest.cs
  Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
Labels: w_inprogress

#329 feat(Cast): update fields to properties and lists to observable
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/ParabolicLineCast.cs
  Runtime/Cast/PhysicsCast.cs
  Runtime/Cast/PointsCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Tracking/Modification/PointNormalRotator.cs
  Tests/Editor/Cast/FixedLineCastTest.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Tracking/Modification/PointNormalRotatorTest.cs
Labels: w_inprogress

#330 feat(Association): update fields to properties and lists to observable
  Runtime/Association/Collection.meta
  Runtime/Association/Collection/GameObjectsAssociationObservableList.cs
  Runtime/Association/Collection/GameObjectsAssociationObservableList.cs.meta
  Runtime/Association/GameObjectsAssociation.cs
  Runtime/Association/GameObjectsAssociationActivator.cs
  Runtime/Association/LoadedXrDeviceAssociation.cs
  Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
Labels: w_inprogress

#327 Feat/obslist inspector
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/package.json
  Editor/Data/Collection.meta
  Editor/Data/Collection/ObservableListEditor.cs
  Editor/Data/Collection/ObservableListEditor.cs.meta
  Editor/Zinnia.Editor.asmdef
Labels: w_inprogress

#299 feat(Collision): add ability to ignore collisions between GameObjects
  Runtime/Tracking/Collision/CollisionIgnorer.cs
  Runtime/Tracking/Collision/CollisionIgnorer.cs.meta
  Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
  Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs.meta
Labels: w_inprogress

#334 feat(Collection): rename events in ObservableList
  Editor/Data/Collection/ObservableListEditor.cs
  Runtime/Action/ActionRegistrar.cs
  Runtime/Action/AllAction.cs
  Runtime/Action/AnyAction.cs
  Runtime/Data/Collection/ObservableCounter.cs
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Tracking/Collision/CollisionIgnorer.cs
  Tests/Editor/Data/Collection/GameObjectObservableCounterTest.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
Labels: w_inprogress

#335 fix(Data): ensure correct list state when emitting inspector events - fixes #333
  Editor/Data/Collection/ObservableListEditor.cs
  Runtime/Data/Collection/ObservableList.cs
Labels: w_inprogress

#336 Fix/obs list logic
  Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Extension/IReadOnlyCollectionExtensions.cs
  Runtime/Tracking/Follow/ObjectFollower.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
  Tests/Editor/Extension/ICollectionExtensionsTest.cs
Labels: w_inprogress

#337 docs(README.md): add instructions of how to run the tests
  README.md
Labels: w_inprogress

#338 feat(Attribute): add additional readonly options to Restricted
  Editor/Data/Attribute/RestrictedAttributeDrawer.cs
  Runtime/Data/Attribute/RestrictedAttribute.cs
Labels: w_inprogress

#339 Chore/change loops
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Cast/FixedLineCast.cs
  Runtime/Data/Type/Transformation/Vector2ToAngle.cs
  Runtime/Haptics/HapticPulser.cs
  Runtime/Process/Moment/MomentProcess.cs
Labels: chore, w_inprogress

#340 chore(general): use ObservableList.NonSubscribableElements instead - resolves #326
  Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs
  Runtime/Haptics/HapticProcessor.cs
  Runtime/Process/Component/GameObjectSourceTargetProcessor.cs
  Runtime/Process/Moment/MomentProcessor.cs
  Runtime/Rule/AllRule.cs
  Runtime/Rule/AnyComponentTypeRule.cs
  Runtime/Rule/AnyRule.cs
  Runtime/Rule/AnyTagRule.cs
  Runtime/Rule/RulesMatcher.cs
  Runtime/Tracking/Follow/ObjectFollower.cs
  Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
  Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
  Runtime/Tracking/Velocity/VelocityTrackerProcessor.cs
  Tests/Editor/Action/Collection/ActionRegistrarSourceObservableListTest.cs
  Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
Labels: w_inprogress

#341 chore(general): fix invalid XML documentation comments
  Runtime/Data/Type/Transformation/CollectionAggregator.cs
  Runtime/Data/Type/Transformation/Vector2Multiplier.cs
  Runtime/Data/Type/Transformation/Vector3Multiplier.cs
  Runtime/Haptics/AudioClipHapticPulser.cs
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Pointer/PointerElement.cs
  Runtime/Rule/RulesMatcher.cs
  Runtime/Tracking/Follow/ObjectFollower.cs
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Runtime/Visual/CameraColorOverlay.cs
  Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
Labels: chore, w_inreview

#342 fix(Tracking): use correct delta time independent of loop type
  Runtime/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocity.cs
Labels: w_inreview

#343 Feat/process improvements - resolves #307 - resolves #308
  Runtime/Process/Moment/MomentProcess.cs
  Tests/Editor/Process/Moment.meta
  Tests/Editor/Process/Moment/MomentProcessTest.cs
  Tests/Editor/Process/Moment/MomentProcessTest.cs.meta
Labels: w_inprogress

#344 chore(Rule): remove TODO comment
  Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
Labels: chore, w_inreview

#345 feat(Tracking): allow GameObject as Target in ObscuranceQuery - resolves #264
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Tests/Editor/Tracking/Query/ObscuranceQueryTest.cs
Labels: w_inprogress

#346 chore(Association): explain why the test results in a warning log
  Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
Labels: chore, w_inreview

#347 feat(CameraRig): add observable list for linked alias association
  Runtime/Tracking/CameraRig/Collection.meta
  Runtime/Tracking/CameraRig/Collection/LinkedAliasAssociationCollectionObservableList.cs
  Runtime/Tracking/CameraRig/Collection/LinkedAliasAssociationCollectionObservableList.cs.meta
Labels: w_inprogress

#348 feat(Modification): remove local CurrentIndex property
  Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
  Tests/Editor/Tracking/Modification/GameObjectStateSwitcherTest.cs
Labels: w_inprogress

#350 fix(Modification): switch from behaviour to component observable list
  Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
  Tests/Editor/Tracking/Modification/ComponentEnabledStateModifierTest.cs
Labels: w_inprogress

#351 feat(Collection): add method to set element or add if empty to list
  Runtime/Data/Collection/ObservableList.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
Labels: w_inprogress

#353 fix(Collision): provide access modifier on internal lists
  Runtime/Tracking/Collision/CollisionIgnorer.cs
Labels: w_inprogress

#354 fix(Query): ensure obscurance target has a valid compound collider
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Tests/Editor/Tracking/Query/ObscuranceQueryTest.cs
Labels: w_inprogress

#355 feat(Collection): provide default value for Clear parameter
  Runtime/Data/Collection/ObservableList.cs
  Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
  Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
  Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
Labels: w_inprogress

#352 Chore/update malimbe
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Utility/InterfaceContainer.cs
Labels: chore, w_inprogress

#356 feat(Extension): ability to queue a behaviour action to run on enable
  Runtime/Extension/BehaviourExtensions.cs
  Runtime/Extension/BehaviourExtensions.cs.meta
  Tests/Editor/Extension/BehaviourExtensionsTest.cs
  Tests/Editor/Extension/BehaviourExtensionsTest.cs.meta
Labels: w_inprogress

#357 Revert "Chore/update malimbe"
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Utility/InterfaceContainer.cs
Labels: w_inprogress

#358 fix(Collision): ensure ignored collisions are resumed on disable
  Runtime/Tracking/Collision/CollisionIgnorer.cs
  Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
Labels: w_inprogress

#360 Chore/update malimbe
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/Editor/Malimbe.MemberChangeMethod.Fody.dll
  Dependencies/Malimbe/package.json
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Utility/InterfaceContainer.cs
Labels: chore, w_inreview

#359 feat(Cast): provide validity data along with hit data - fixes #104
  Runtime/Cast/FixedLineCast.cs
  Runtime/Cast/ParabolicLineCast.cs
  Runtime/Cast/PointsCast.cs
  Runtime/Cast/StraightLineCast.cs
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Tracking/Modification/PointNormalRotator.cs
  Tests/Editor/Cast/ParabolicLineCastTest.cs
  Tests/Editor/Cast/StraightLineCastTest.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Tracking/Modification/PointNormalRotatorTest.cs
Labels: w_inprogress

#361 fix(Action): prevent null actions being subscribed to/from
  Runtime/Action/Action.cs
Labels: w_inprogress

#364 chore(general): remove unused namespace imports
  Runtime/Haptics/TimedHapticProcess.cs
  Tests/Editor/Data/Collection/GameObjectRelationsTest.cs
  Tests/Editor/Tracking/Velocity/ComponentTrackerProxyTest.cs
Labels: chore, w_inreview

#365 chore(Dependencies): update Malimbe to version 9.4.2
  Dependencies/Malimbe/CHANGELOG.md
  Dependencies/Malimbe/Editor/Malimbe.FodyRunner.UnityIntegration.dll
  Dependencies/Malimbe/package.json
Labels: chore, w_inreview

#366 Fix/gc allocs
  Runtime/Action/Action.cs
  Runtime/Cast/PointsCast.cs
  Runtime/Data/Collection/ObservableList.cs
  Runtime/Data/Type/AllocationFreeReadOnlyList.cs
  Runtime/Data/Type/AllocationFreeReadOnlyList.cs.meta
  Runtime/Extension/GameObjectExtensions.cs
  Runtime/Extension/ListExtensions.cs
  Runtime/Extension/ListExtensions.cs.meta
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Rule/AnyComponentTypeRule.cs
  Runtime/Tracking/Query/ObscuranceQuery.cs
  Runtime/Visual/PointsRenderer.cs
Labels: w_inreview

#367 chore(Tracking): fix unresolved method error in a test
  Tests/Editor/Tracking/Velocity/ComponentTrackerProxyTest.cs
Labels: chore, w_inreview

#368 feat(Utility): simplify interface container drawers - resolves #302
  Editor/Data/Attribute/TypePickerAttributeDrawer.cs
  Editor/Rule.meta
  Editor/Rule/RuleContainerDrawer.cs
  Editor/Rule/RuleContainerDrawer.cs.meta
  Editor/Utility/InterfaceContainerDrawer.cs
  Editor/Utility/PickerWindow.cs
  Editor/Utility/PickerWindow.cs.meta
  Editor/Utility/TypePickerWindow.cs
  Runtime/Data/Attribute/TypePickerAttribute.cs
Labels: w_inprogress

#369 Fix/non alloc readonlylist usage
  Editor/Utility/PickerWindow.cs
  Runtime/Data/Type/AllocationFreeReadOnlyList.cs
  Runtime/Pointer/ObjectPointer.cs
  Tests/Editor/Pointer/ObjectPointerTest.cs
  Tests/Editor/Visual/PointsRendererTest.cs
Labels: w_inprogress

#363 Fix/pointers
  Runtime/Pointer/ObjectPointer.cs
  Runtime/Visual/PointsRenderer.cs
Labels: w_inreview

#370 fix(Utility): error log when drawing field for component picker
  Editor/Utility/InterfaceContainerDrawer.cs
Labels: w_inprogress
